# Generated by Django 2.2.1 on 2019-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='首页轮播标题')),
                ('deatil', models.CharField(max_length=40, verbose_name='详情描述')),
            ],
        ),
        migrations.CreateModel(
            name='chose_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='小标题')),
                ('deatil', models.TextField(max_length=300, verbose_name='小标题描述')),
            ],
        ),
        migrations.CreateModel(
            name='imglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpath', models.ImageField(upload_to='ads', verbose_name='图片列表(成品图)')),
            ],
        ),
        migrations.CreateModel(
            name='learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='照片主题')),
                ('deatil', models.CharField(max_length=40, verbose_name='照片描述')),
                ('imgpath', models.ImageField(upload_to='ads', verbose_name='照片路径')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='新闻标题')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('text', models.TextField(max_length=500, verbose_name='新闻内容')),
                ('imgpath', models.ImageField(upload_to='ads', verbose_name='新闻图片路径')),
            ],
        ),
        migrations.CreateModel(
            name='pro_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='小标题')),
                ('imgpath', models.ImageField(upload_to='ads', verbose_name='图片路径')),
                ('deatil1', models.CharField(max_length=50, verbose_name='描述1')),
                ('deatil2', models.CharField(max_length=50, verbose_name='描述2')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpath', models.ImageField(upload_to='ads', verbose_name='服务图片')),
                ('title', models.CharField(max_length=30, verbose_name='服务小标题')),
                ('deatil', models.CharField(max_length=100, verbose_name='服务描述')),
            ],
        ),
        migrations.CreateModel(
            name='us_suppot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='能提供的服务')),
            ],
        ),
        migrations.CreateModel(
            name='us_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='成员名字')),
                ('deatil', models.CharField(max_length=300, verbose_name='成员描述')),
                ('imgpath', models.ImageField(upload_to='ads', verbose_name='成员自画像')),
            ],
        ),
    ]
