# Generated by Django 2.2.1 on 2019-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='imgpath',
            field=models.ImageField(height_field=453, upload_to='ads', verbose_name='照片路径', width_field=385),
        ),
    ]
