# Generated by Django 2.2.1 on 2019-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_auto_20190529_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='imgpath',
            field=models.ImageField(height_field='453px', upload_to='ads', verbose_name='照片路径', width_field='385px'),
        ),
    ]
